name: Generate Racing Contribution

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Generate racing graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: abhay-gautam0
          outputs: |
            dist/racing.svg


      - name: Add racing effect
        run: |
          sed -i 's/<\/svg>/<text x="20" y="30" font-size="25">🏎️💨 ABHAY CODING CIRCUIT<\/text><\/svg>/' dist/racing.svg


      - name: Deploy output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
