name: Generate Racing Track

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write


jobs:
  generate:
    runs-on: ubuntu-latest


    steps:

      - name: Generate Race Track
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: abhay-gautam0

          outputs: |
            dist/racing.svg?palette=github-dark


      - name: Customize Racing Track
        run: |

          sed -i 's/<\/svg>/<text x="50%" y="30" text-anchor="middle" font-size="22" fill="white">🏁 ABHAY GRAND PRIX 🏁<\/text><\/svg>/' dist/racing.svg


      - name: Deploy Race Track
        uses: peaceiris/actions-gh-pages@v4

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_branch: output
          publish_dir: ./dist
