name: Racing Track Contribution

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Create Racing SVG
        run: |

          mkdir -p dist

          cat > dist/racing.svg <<'EOF'
          <svg width="900" height="260"
          xmlns="http://www.w3.org/2000/svg">

          <rect width="100%" height="100%"
          fill="#0d1117"/>


          <text x="280" y="35"
          fill="white"
          font-size="25">
          🏁 ABHAY GRAND PRIX 🏁
          </text>


          <!-- Track -->
          <path d="
          M100 130
          C200 50,350 50,450 130
          C550 210,700 210,800 130"

          stroke="#555"
          stroke-width="45"
          fill="none"
          stroke-linecap="round"/>


          <!-- Road Line -->
          <path d="
          M100 130
          C200 50,350 50,450 130
          C550 210,700 210,800 130"

          stroke="white"
          stroke-width="4"
          stroke-dasharray="20"
          fill="none"/>


          <!-- Car -->

          <text>

          <animateMotion
          dur="8s"
          repeatCount="indefinite"

          path="
          M100 130
          C200 50,350 50,450 130
          C550 210,700 210,800 130"/>

          🏎️💨

          </text>


          <text x="80"
          y="210"
          fill="#39ff14"
          font-size="18">

          Python 🐍 | SQL 🗄️ | Power BI 📊

          </text>


          <text x="720"
          y="130"
          font-size="30">
          🏁
          </text>


          </svg>
          EOF


      - name: Deploy

        uses: peaceiris/actions-gh-pages@v4

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_branch: output

          publish_dir: ./dist
